input {
  http {
    port => 8080
    codec => json
  }
}

filter {
  if [event.dataset] == "errors" or [log.level] == "error" {
    mutate {
      add_tag => ["error"]
    }
  }

  if [event.dataset] == "auth" {
    mutate {
      add_tag => ["auth"]
    }
  }

  if [event.dataset] == "security" {
    mutate {
      add_tag => ["security"]
    }
  }

  if ![event.dataset] {
    mutate {
      replace => { "event.dataset" => "server" }
    }
  }
}

output {
  stdout {
    codec => rubydebug
  }

  if [event.dataset] == "server" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "elastic"
      password => "${ELASTIC_PASSWORD}"
      index => "ft-transcendence-server-%{+YYYY.MM.dd}"
    }
  } else if [event.dataset] == "auth" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "elastic"
      password => "${ELASTIC_PASSWORD}"
      index => "ft-transcendence-auth-%{+YYYY.MM.dd}"
    }
  } else if [event.dataset] == "security" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "elastic"
      password => "${ELASTIC_PASSWORD}"
      index => "ft-transcendence-security-%{+YYYY.MM.dd}"
    }
  } else if [event.dataset] == "game" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "elastic"
      password => "${ELASTIC_PASSWORD}"
      index => "ft-transcendence-game-%{+YYYY.MM.dd}"
    }
  } else if [event.dataset] == "errors" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "elastic"
      password => "${ELASTIC_PASSWORD}"
      index => "ft-transcendence-errors-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "elastic"
      password => "${ELASTIC_PASSWORD}"
      index => "ft-transcendence-server-%{+YYYY.MM.dd}"
    }
  }
}