global:
  scrape_interval:      15s     # How often Prometheus will scrape targets
  evaluation_interval:  15s     # How often Prometheus will evaluate rules
  #external_labels:
  #  env: dev                    # Attaches an 'env' label with value 'dev' to all metrics and alerts

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: prometheus                # Prometheus monitoring itself. 
    static_configs:                     # Prometheus expects metrics to be available on targets on a path of /metrics
      - targets: ['localhost:9090']     # So this default job is scraping via the URL: http://localhost:9090/metrics 

  - job_name: our_beautiful_server
    static_configs:
      - targets: ['app:3000']

  - job_name: postgres-exporter
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']