{
 "title": "cadvisor dashboard",
 "description": "I created this cadvisor dashboard to show everything scraped from cadvisor.\r\n\r\n- Expanding all the rows may consume too much resources.\r\n- Limit the containers by selecting compose_project.\r\n- First few rows are stacked. Container rows are not.\r\n\r\nIf you have any issues or suggestions, please email mail@maoyin.eu.",
 "tags": [
  "cadvisor",
  "docker",
  "prometheus",
  "container"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host_instance",
    "label": "host_instance",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},instance)"
    }
   },
   {
    "name": "compose_project",
    "label": "compose_project",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$host_instance\"},container_label_com_docker_compose_project)"
    }
   },
   {
    "name": "container_name",
    "label": "container_name",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$host_instance\", container_label_com_docker_compose_project=~\"$compose_project\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "container_start_time",
     "type": "bargauge",
     "description": "Start time of the container since unix epoch in seconds.",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (name) (container_start_time_seconds{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}) * 1000",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_last_seen",
     "type": "bargauge",
     "description": "Last time a container was seen by the exporter",
     "gridPos": { "h": 9, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (name) (container_last_seen{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}) * 1000",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_tasks_state",
     "type": "timeseries",
     "description": "Number of tasks in given state\nnot working: https://github.com/google/cadvisor/issues/2739",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "sum by (state)(container_tasks_state{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "container_oom_events_total",
     "type": "timeseries",
     "description": "Count of out of memory events observed for the container",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_oom_events_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} received"
      }
     ]
    },
    {
     "title": "container_scrape_error",
     "type": "timeseries",
     "description": "1 if there was an error while getting container metrics, 0 otherwise",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "container_scrape_error", "legendFormat": "{{job}}" }
     ]
    }
   ]
  },
  {
   "title": "cpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "container_cpu_system",
     "type": "timeseries",
     "description": "Cumulative system cpu time consumed in seconds.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_cpu_system_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_cpu_user",
     "type": "timeseries",
     "description": "Cumulative system cpu time consumed in seconds.",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_cpu_user_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_cpu_usage",
     "type": "timeseries",
     "description": "Cumulative cpu time consumed in seconds.",
     "gridPos": { "h": 9, "w": 7, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_cpu_usage_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_cpu check",
     "type": "timeseries",
     "description": "Validate usage = user + system",
     "gridPos": { "h": 9, "w": 3, "x": 21, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_cpu_usage_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval])) - on (name) (max by (name) (rate(container_cpu_user_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval])) + on (name) max by (name) (rate(container_cpu_system_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))) ",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_cpu_cfs_periods_total",
     "type": "timeseries",
     "description": " Number of elapsed enforcement period intervals.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_cpu_cfs_periods_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_cpu_cfs_throttled_periods_total",
     "type": "timeseries",
     "description": "Number of throttled period intervals.",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_cpu_cfs_throttled_periods_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_cpu_cfs_throttled_periods_total",
     "type": "timeseries",
     "description": "Number of throttled period intervals.",
     "gridPos": { "h": 9, "w": 7, "x": 14, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_cpu_cfs_throttled_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_cpu_load_average_10s",
     "type": "timeseries",
     "description": "Not enabled\nhttps://github.com/google/cadvisor/issues/2529",
     "gridPos": { "h": 9, "w": 3, "x": 21, "y": 11 },
     "targets": [
      {
       "expr": "max by (name) (container_cpu_load_average_10s{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "container_memory_failcnt",
     "type": "timeseries",
     "description": "Number of memory usage hits limits",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_memory_failcnt{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_failures_total",
     "type": "timeseries",
     "description": "Cumulative count of memory allocation failures.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_memory_failures_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_max_usage_bytes",
     "type": "timeseries",
     "description": " Maximum memory usage recorded in bytes",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_max_usage_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_usage_bytes",
     "type": "timeseries",
     "description": "Current memory usage in bytes, including all memory regardless of when it was accessed",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_usage_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_working_set_bytes",
     "type": "timeseries",
     "description": "Current working set in bytes.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_working_set_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_rss",
     "type": "timeseries",
     "description": "Size of RSS in bytes.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_rss{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_mapped_file",
     "type": "timeseries",
     "description": "Size of memory mapped files in bytes.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_mapped_file{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_cache",
     "type": "timeseries",
     "description": "Number of bytes of page cache memory.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_cache{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_swap",
     "type": "timeseries",
     "description": "Container swap usage in bytes.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_swap{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_spec_memory_limit",
     "type": "timeseries",
     "description": "Memory limit for the container.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_spec_memory_limit_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_spec_memory_reservation_limit_bytes",
     "type": "timeseries",
     "description": "Memory reservation limit for the container.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_spec_memory_reservation_limit_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "container_spec_memory_swap_limit_bytes",
     "type": "timeseries",
     "description": "Memory swap limit for the container.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_spec_memory_swap_limit_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "container_network_receive_bytes_total, container_network_transmit_bytes_total",
   "type": "timeseries",
   "description": "Cumulative count of bytes received, Cumulative count of bytes transmitted",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (name) (rate(container_network_receive_bytes_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
     "legendFormat": "{{name}} received"
    },
    {
     "expr": "- max by (name) (rate(container_network_transmit_bytes_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
     "legendFormat": "{{name}} transmitted"
    }
   ]
  },
  {
   "title": "container_network_receive_packets_total, container_network_transmit_packets_total",
   "type": "timeseries",
   "description": "Cumulative count of packets received, Cumulative count of packets transmitted",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (name) (rate(container_network_receive_packets_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
     "legendFormat": "{{name}} received"
    },
    {
     "expr": "- max by (name) (rate(container_network_transmit_packets_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
     "legendFormat": "{{name}} transmitted"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "container_network_receive_errors_total, container_network_transmit_errors_total",
   "type": "timeseries",
   "description": "Cumulative count of errors encountered while receiving, Cumulative count of errors encountered while transmitting",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (name) (rate(container_network_receive_errors_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
     "legendFormat": "{{name}} received"
    },
    {
     "expr": "- max by (name) (rate(container_network_transmit_errors_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
     "legendFormat": "{{name}} transmitted"
    }
   ]
  },
  {
   "title": "container_network_receive_packets_dropped_total, container_network_transmit_packets_dropped_total",
   "type": "timeseries",
   "description": "Cumulative count of packets dropped while receiving, Cumulative count of packets dropped while transmitting",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (name) (rate(container_network_receive_packets_dropped_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
     "legendFormat": "{{name}} received"
    },
    {
     "expr": "- max by (name) (rate(container_network_transmit_packets_dropped_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
     "legendFormat": "{{name}} transmitted"
    }
   ]
  },
  {
   "title": "blkio",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "container_blkio_device_usage_total",
     "type": "timeseries",
     "description": "Blkio Device bytes usage",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_blkio_device_usage_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "fs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "container_fs_inodes_free, container_fs_inodes_total",
     "type": "timeseries",
     "description": "Number of available Inodes, Number of Inodes",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 132 },
     "targets": [
      {
       "expr": "max by (name) (container_fs_inodes_free{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}} free"
      },
      {
       "expr": "max by (name) (container_fs_inodes_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_fs_limit",
     "type": "timeseries",
     "description": "Number of bytes that can be consumed by the container on this filesystem.",
     "gridPos": { "h": 9, "w": 3, "x": 3, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_fs_limit_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_fs_io_current",
     "type": "timeseries",
     "description": "https://github.com/google/cadvisor/issues/1403#issuecomment-1752155206",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 132 },
     "targets": [
      {
       "expr": "max by (name) (container_fs_io_current{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_fs_usage",
     "type": "timeseries",
     "description": "Cumulative count of seconds spent doing I/Os, Cumulative weighted I/O time in seconds",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_usage_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_fs_io",
     "type": "timeseries",
     "description": "Cumulative count of seconds spent doing I/Os, Cumulative weighted I/O time in seconds",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_io_time_weighted_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} weighed"
      }
     ]
    },
    {
     "title": "container_fs_read_seconds, container_fs_write_seconds",
     "type": "timeseries",
     "description": "Cumulative count of seconds spent reading or writing",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_read_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} read"
      },
      {
       "expr": "max by (name) (-rate(container_fs_write_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} write"
      }
     ]
    },
    {
     "title": "container_fs_sector_reads_total, container_fs_sector_writes_total",
     "type": "timeseries",
     "description": "Cumulative count of sector reads or writes completed, ",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_sector_reads_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} reads"
      },
      {
       "expr": "- max by (name) (rate(container_fs_sector_writes_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} writes"
      }
     ]
    },
    {
     "title": "container_fs_reads_total, container_fs_writes_total",
     "type": "timeseries",
     "description": "Cumulative count of reads or writes completed",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_reads_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} reads"
      },
      {
       "expr": "- max by (name) (rate(container_fs_writes_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} writes"
      }
     ]
    },
    {
     "title": "container_fs_reads_merged_total, container_fs_writes_merged_total",
     "type": "timeseries",
     "description": "Cumulative count of reads or writes merged",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_reads_merged_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} reads"
      },
      {
       "expr": "- max by (name) (rate(container_fs_writes_merged_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} writes"
      }
     ]
    }
   ]
  },
  {
   "title": "Container $container_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "container_name",
   "collapsed": true,
   "panels": [
    {
     "title": "docker compose project",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_start_time_seconds{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "docker compose container number",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_start_time_seconds{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "docker compose oneoff",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_start_time_seconds{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "container_tasks_state",
     "type": "timeseries",
     "description": "Number of tasks in given state\nnot working: https://github.com/google/cadvisor/issues/2739",
     "gridPos": { "h": 4, "w": 2, "x": 9, "y": 34 },
     "targets": [
      {
       "expr": "sum by (state)(container_tasks_state{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "docker compose version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 11, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_start_time_seconds{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "docker compose project config files",
     "type": "stat",
     "gridPos": { "h": 2, "w": 11, "x": 13, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_start_time_seconds{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "container maintainer",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 3, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_start_time_seconds{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "docker compose project working dir",
     "type": "stat",
     "gridPos": { "h": 2, "w": 11, "x": 13, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_start_time_seconds{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "docker compose service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_start_time_seconds{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "container_start_time",
     "type": "stat",
     "description": "Start time of the container since unix epoch in seconds.",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (name) (container_start_time_seconds{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}) * 1000",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_last_seen",
     "type": "stat",
     "description": "Last time a container was seen by the exporter",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (name) (container_last_seen{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}) * 1000",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "docker compose config hash",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 9, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_start_time_seconds{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "image",
     "type": "stat",
     "gridPos": { "h": 2, "w": 9, "x": 15, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_start_time_seconds{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "docker compose image",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 9, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_start_time_seconds{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "build version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 9, "x": 15, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_start_time_seconds{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "container_cpu",
     "type": "timeseries",
     "description": "Cumulative system cpu time consumed in seconds.",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_cpu_system_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} system"
      },
      {
       "expr": "max by (name) (rate(container_cpu_user_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} user"
      },
      {
       "expr": "max by (name) (rate(container_cpu_usage_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} usage"
      }
     ]
    },
    {
     "title": "container_cpu_cfs_periods_total",
     "type": "timeseries",
     "description": " Number of elapsed enforcement period intervals.",
     "gridPos": { "h": 6, "w": 4, "x": 9, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_cpu_cfs_periods_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_cpu_cfs_throttled_periods_total",
     "type": "timeseries",
     "description": "Number of throttled period intervals.",
     "gridPos": { "h": 6, "w": 4, "x": 13, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_cpu_cfs_throttled_periods_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_cpu_cfs_throttled_periods_total",
     "type": "timeseries",
     "description": "Number of throttled period intervals.",
     "gridPos": { "h": 6, "w": 4, "x": 17, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_cpu_cfs_throttled_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_cpu_load_average_10s",
     "type": "timeseries",
     "description": "Not enabled\nhttps://github.com/google/cadvisor/issues/2529",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 87 },
     "targets": [
      {
       "expr": "max by (name) (container_cpu_load_average_10s{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_failcnt",
     "type": "timeseries",
     "description": "Number of memory usage hits limits",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_memory_failcnt{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_failures_total",
     "type": "timeseries",
     "description": "Cumulative count of memory allocation failures.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_memory_failures_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_max_usage_bytes",
     "type": "timeseries",
     "description": " Maximum memory usage recorded in bytes",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_max_usage_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_usage_bytes",
     "type": "timeseries",
     "description": "Current memory usage in bytes, including all memory regardless of when it was accessed",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_usage_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_working_set_bytes",
     "type": "timeseries",
     "description": "Current working set in bytes.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_working_set_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_rss",
     "type": "timeseries",
     "description": "Size of RSS in bytes.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_rss{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_mapped_file",
     "type": "timeseries",
     "description": "Size of memory mapped files in bytes.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_mapped_file{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_cache",
     "type": "timeseries",
     "description": "Number of bytes of page cache memory.",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_cache{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_memory_swap",
     "type": "timeseries",
     "description": "Container swap usage in bytes.",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_memory_swap{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_spec_memory_limit",
     "type": "timeseries",
     "description": "Memory limit for the container.",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_spec_memory_limit_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_spec_memory_reservation_limit_bytes",
     "type": "timeseries",
     "description": "Memory reservation limit for the container.",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_spec_memory_reservation_limit_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "container_spec_memory_swap_limit_bytes",
     "type": "timeseries",
     "description": "Memory swap limit for the container.",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_spec_memory_swap_limit_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_network_receive_bytes_total, container_network_transmit_bytes_total",
     "type": "timeseries",
     "description": "Cumulative count of bytes received, Cumulative count of bytes transmitted",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_network_receive_bytes_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} received"
      },
      {
       "expr": "- max by (name) (rate(container_network_transmit_bytes_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} transmitted"
      }
     ]
    },
    {
     "title": "container_network_receive_packets_total, container_network_transmit_packets_total",
     "type": "timeseries",
     "description": "Cumulative count of packets received, Cumulative count of packets transmitted",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_network_receive_packets_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} received"
      },
      {
       "expr": "- max by (name) (rate(container_network_transmit_packets_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} transmitted"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "container_network_receive_errors_total, container_network_transmit_errors_total",
     "type": "timeseries",
     "description": "Cumulative count of errors encountered while receiving, Cumulative count of errors encountered while transmitting",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_network_receive_errors_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} received"
      },
      {
       "expr": "- max by (name) (rate(container_network_transmit_errors_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} transmitted"
      }
     ]
    },
    {
     "title": "container_network_receive_packets_dropped_total, container_network_transmit_packets_dropped_total",
     "type": "timeseries",
     "description": "Cumulative count of packets dropped while receiving, Cumulative count of packets dropped while transmitting",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_network_receive_packets_dropped_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} received"
      },
      {
       "expr": "- max by (name) (rate(container_network_transmit_packets_dropped_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} transmitted"
      }
     ]
    },
    {
     "title": "container_blkio_device_usage_total",
     "type": "timeseries",
     "description": "Blkio Device bytes usage",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_blkio_device_usage_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_fs_inodes_free, container_fs_inodes_total",
     "type": "timeseries",
     "description": "Number of available Inodes, Number of Inodes",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 110 },
     "targets": [
      {
       "expr": "max by (name) (container_fs_inodes_free{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}} free"
      },
      {
       "expr": "max by (name) (container_fs_inodes_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_fs_limit",
     "type": "timeseries",
     "description": "Number of bytes that can be consumed by the container on this filesystem.",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (container_fs_limit_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_fs_io_current",
     "type": "timeseries",
     "description": "https://github.com/google/cadvisor/issues/1403#issuecomment-1752155206",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 110 },
     "targets": [
      {
       "expr": "max by (name) (container_fs_io_current{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_fs_usage",
     "type": "timeseries",
     "description": "Cumulative count of seconds spent doing I/Os, Cumulative weighted I/O time in seconds",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_usage_bytes{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "container_fs_io",
     "type": "timeseries",
     "description": "Cumulative count of seconds spent doing I/Os, Cumulative weighted I/O time in seconds",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_io_time_weighted_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} weighed"
      }
     ]
    },
    {
     "title": "container_fs_read_seconds, container_fs_write_seconds",
     "type": "timeseries",
     "description": "Cumulative count of seconds spent reading or writing",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_read_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} read"
      },
      {
       "expr": "max by (name) (-rate(container_fs_write_seconds_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} write"
      }
     ]
    },
    {
     "title": "container_fs_sector_reads_total, container_fs_sector_writes_total",
     "type": "timeseries",
     "description": "Cumulative count of sector reads or writes completed, ",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_sector_reads_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} reads"
      },
      {
       "expr": "- max by (name) (rate(container_fs_sector_writes_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} writes"
      }
     ]
    },
    {
     "title": "container_fs_reads_total, container_fs_writes_total",
     "type": "timeseries",
     "description": "Cumulative count of reads or writes completed",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_reads_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} reads"
      },
      {
       "expr": "- max by (name) (rate(container_fs_writes_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} writes"
      }
     ]
    },
    {
     "title": "container_fs_reads_merged_total, container_fs_writes_merged_total",
     "type": "timeseries",
     "description": "Cumulative count of reads or writes merged",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (name) (rate(container_fs_reads_merged_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} reads"
      },
      {
       "expr": "- max by (name) (rate(container_fs_writes_merged_total{instance=~\"$host_instance\", name=~\"$container_name\", container_label_com_docker_compose_project=~\"$compose_project\"}[$__rate_interval]))",
       "legendFormat": "{{name}} writes"
      }
     ]
    }
   ]
  }
 ]
}