{
 "title": "Transcendence overview",
 "tags": [ "CUSTOM" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global Status Map",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "pg_up", "legendFormat": "Database" },
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Requests per second by route by status code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"our_beautiful_server\"}[5m])) by (status_code, route)",
     "legendFormat": "{{route}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "description": "The response time for 95% of requests is equal to or less than the specified value",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"our_beautiful_server\"}[5m])) by (le, route))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources by Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "description": "This measures the actual physical RAM currently occupied by the process. A constantly rising line (steps) without drops typically indicates a memory leak in the application.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Container",
   "type": "timeseries",
   "description": "Shows the percentage of CPU resources used by each container. A value of 100% represents full usage of one CPU core. Sudden spikes here often correlate with high latency or heavy processing tasks (like active game calculations).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\"}[5m])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name!=\"\"}[5m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alert Rules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  { "title": "Alert rules", "type": "alertlist", "gridPos": { "h": 12, "w": 14, "x": 0, "y": 36 } }
 ]
}